### PR TITLE
Ivi manager protocol v2

### PR DESCRIPTION
**Pull request by eucan**
I added orientation requests and events to ivi-manager protocol

### CODE REVIEW

**Comment by mfiedler-xse** [comment]
Only a single ivi_manager_layer and a single ivi_manager_surface are
allowed per ivi_manager. So they are more like some additional 
namespaces for ivi_manager.
Would it make sense to move all ivi_manager_surface requests and events and all ivi_manager_layer requests and events to ivi_manager and extend the names with a corresponding prefix 'surface' and 'layer' ?

**Comment by mfiedler-xse** [comment]
The comment for the ivi_manager_surface.configuration event suggests that width and hight reflect the size the client was requested to resize its buffer to, not the actual surface size. But from the implementation is seems like the configuration event informs about the actual current surface size.
The implementation might make more sense as there would be no other event for the ivi_manager client to find out the real surface size.

**Comment by mfiedler-xse** [comment]
Shall update events for render order (e.g. surface_added) also be send in sync mode?

**Comment by efriedrich** [comment]
The name ivi_manager is to generic, I think something like ivi_wmanager (w for window)

**Comment by eucan** [comment]
I will merge layer and surface interfaces to ivi-manager interface. I will send a new PR with these changes.

In current implementation, it is not feasible to update render order all the time. Because ivi-shell sends an event with the information that a surface is added to layer. There is no information where in layer render order this surface added to. We have to either modify ivi-shell code or track render order in ivi-controller.

Both options are not optimal because:
- updating ivi-shell cumbersome and takes time. We have to release the update for next compliance update
- tracking render order is also bad. it is already tracked at ivi-layout. they should be in sync etc.

In my opinion, ivi_manager is ok and not too generic because it is a wayland protocol. It is clear that it manages compositor content. But we can change the name. No problem.

what about ivi_wm instead of ivi_wmanager? I like short names then function names would be also short.
Therefore, I want to skip it for now. In future we can change it.

**Comment by efriedrich** [comment]
lets go for ivi_wm and we should change this before merging this implementation, changing the name later could cause some confusion and explanation efforts which we should avoid ( we have already enough such efforts :-) )

**Pull request closed without merging**
