### PR TITLE
Deprecate ilm client v1

### PR DESCRIPTION
**Pull request by eucan**
This PR
- bumps the version to 1.11 stable release and opens the repo to new work
- deprecates ilmClient API
- removes ilmClient APIs from EGLWLInputEventExample, EGLWLMockNavigation and tests

### CODE REVIEW

**Comment by efriedrich** [comment]
HI Emre, this pull request has 3 different thinks in one, 
Could you please slit this into 3 or even 4 separate pull request?
1. version dump
2. deprecate ilmClient 
3. install new helper library and export header files
4. remove the dependencies to ilmClients from the example

Also before we will set the ilmClient api to deprecated I would have to talk ones with Genivi architects, to avoid Genivi compliance violation, other wise new 1.11.0 tag might be rejected for GDP

**Comment by eucan** [comment]
Hi Eugen,

This first patch increases the version number. Therefore, there is no reason that GDP might reject v1.11.

In my opinion, we have to make the changes first and apply for a compliance update later. We did previously like that. Anyway we are not breaking backwards compatibility with these changes. The applications will get only compiler warnings, if they are using deprecated APIs.

I can create more PRs. No problem. But at least 2. and 4. should be together.
It is actually more appropriate that you or Natsume-san bumps the version...

**Comment by efriedrich** [comment]
@eucan 

> This first patch increases the version number. Therefore, there is no reason that GDP might reject v1.11.

but having one pull request it not possible to apply only this change, right...

> In my opinion, we have to make the changes first and apply for a compliance update later. We did previously like that. Anyway we are not breaking backwards compatibility with these changes. The applications will get only compiler warnings, if they are using deprecated APIs.

agree, we could even apply following order ( I should not use numbered list in my replay :-)):
3. install new helper library and export header files
4. remove the dependencies to ilmClients from the example
1. version dump
2. deprecate ilmClient 
technically 2. and 4. are not dependent, only if you apply 2. before 4. you will get some warning as you mentioned, but it is safe to apply 

> It is actually more appropriate that you or Natsume-san bumps the version... 

What do mean by this? Last bump has only the version update and then a tag

**Comment by wnatsume** [comment]
Would you create 4 PRs, Emre-san? I will add review comment to each PR.
Patch for bump version is also fine. I will announce 1.11.0 after review and merge.
Thanks

**Comment by efriedrich** [comment]
new PR where created, closing this one

**Pull request closed without merging**
