### PR TITLE
Fix set surface & layer destination rectangle of ivi-controller

### PR DESCRIPTION
**Pull request by t-oss**
Refer to weston compositor, negative detection for x & y params only needed for set source rectangle

### CODE REVIEW

**Comment by eucan** [comment]
This is not a bug. It is a feature.. (:
If position parameters are set to negative values, old values are used instead so that you can do e.g.:
LayerManagerControl set surface 10 500 -1 -1 -1
Then only x position of the surface is changed.

**Comment by t-oss** [comment]
Maybe it's caused by someone who removed the "set position" feature, but implement like this is so strange.
And how could you handling the case that moving part of the window(surface) outside of the screen?

**Comment by eucan** [comment]
You can handle it via setting source rectangle.

**Comment by t-oss** [comment]
If so, you need to set destination region along with source region to keep the output not abnormality.
And if there is some scaling, it's very difficult to control.

What's more, not all wayland clients can handling set source/destination region  correctly, sometime it will cause a recreation for EGL client. it increase the difficult for controlling too.

**Pull request closed without merging**
