### PR TITLE
LayerManagerControl: add two subcmd for add/remove a surface to/from a layer.

### PR DESCRIPTION
**Pull request by zeerd**
for more testing from the command line.

### CODE REVIEW

**Comment by efriedrich** [comment]
Hi zeerd,
thanks for the patch, looks good so far,
only one comment:
could you please prefix you patch with "LayerManagerControl:"

**Comment by zeerd** [comment]
i am not sure how to change it.
need i close this one and pull a new request again?

**Comment by zeerd** [comment]
Hi @efriedrich 

OK, seems it worked.

**Comment by efriedrich** [comment]
Review-by: Eugen Friedrich <efriedrich@de.adit-jv.com>
Acked-by: Eugen Friedrich <efriedrich@de.adit-jv.com>

**Comment by zeerd** [comment]
Hi,  @efriedrich 

I added it.

**Pull request merged**
