### PR TITLE
XDG Support for ivi-shell: ivi-id-agent for weston v6

### PR DESCRIPTION
**Pull request by mtey**
This is a reference implementation of an ivi-id-agent plugin. It
creates surface-ids for desktop-surfaces depending on the configuration
provided in "weston.ini". For more please refer to the reference
implementation in this commit.

The only public interface available is the "id_agent_module_init"
function. It is responsible for initialization of structs and reading
the configuration.

In the reference "weston.ini" two types of configurations can be found:

[desktop-app] is used to configure a particular application. Therefore
the desired surface-id must be provided. Moreover "app-title" is the
title that is provided by the desktop application (xdg-protocol).
"app-id" behaves accordingly. Although both parameters can be set, it
is not mandatory. Finally at least one has to be set.

[desktop-app-default] enables the id-agent to generate generic
surface-ids for unconfigured applications, e.g. for development. This
tag is optional. To generate the id an interval starting from
"default-surface-id" to "default-surface-id-max" is used. The id is
incremented until the interval is exceeded.

In the function "get_id" a surface-id is assigned by means of the
configuration. It can be adjusted, if another behavior is desired.
In this plugin the parameters, that are described above, are evaluated.

To use these patches please also apply the dedicated patches for
weston: https://github.com/mtey/weston/tree/xdg_support_ivi_id_agent
Since libweston-desktop is used to introduce desktop-surface support,
xdg-protocol is supported.

More Info:
https://wiki.automotivelinux.org/_media/agl-distro/agl_amm_xdg_support_a04.pdf

### CODE REVIEW

**Comment by mtey** [comment]
Dependent on Weston MR: https://gitlab.freedesktop.org/wayland/weston/merge_requests/86

**Comment by bhupiister** [comment]
If i want to run chromium browser on weston 10.0.1 with wayland-ivi-extension 2.3.1. Do i need to build weston with patches for xdg desktop? 

What do we need to change in Weston.ini for running chromium browser?

**Comment by efriedrich** [comment]
@bhupiister not sure if chromium browser is able to run on weston at all!?
even it is chromium supports wayland it would need some wayland protocols to be supported by the compositor, the xdg protocol is typically not enough for desktop applications. 
so typically a chromium installation will support some GUI framework like gnome, kde, mate which providing wayland support and also come with its own wayland compositor, they will support xdg protocol but also a set of additional protocols which  are not supported by weston.

**Comment by bhupiister** [comment]
> @bhupiister not sure if chromium browser is able to run on weston at all!? even it is chromium supports wayland it would need some wayland protocols to be supported by the compositor, the xdg protocol is typically not enough for desktop applications. so typically a chromium installation will support some GUI framework like gnome, kde, mate which providing wayland support and also come with its own wayland compositor, they will support xdg protocol but also a set of additional protocols which are not supported by weston.

Well it does work well on normal Weston desktop shell on wayland. I am having issues on the ivi-shell and ivi-controller on wayland. It does run for the first time, but then it gives below error

```
$ WAYLAND_DISPLAY=wayland-0 chromium --use-gl=egl --ozone-platform=wayland --in-process-gpu www.google.com
[328:372:1106/032615.159552:ERROR:bus.cc(398)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[328:372:1106/032615.161190:ERROR:bus.cc(398)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[328:362:1106/032615.177154:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[328:362:1106/032615.177265:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[328:362:1106/032615.348613:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[328:362:1106/032615.356354:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[328:328:1106/032615.571872:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
[328:429:1106/032615.831765:ERROR:bus.cc(398)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[328:429:1106/032615.836475:ERROR:bus.cc(398)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[328:429:1106/032615.842669:ERROR:bus.cc(398)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[328:429:1106/032615.843888:ERROR:bus.cc(398)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[328:429:1106/032615.846824:ERROR:bus.cc(398)] Failed to connect to the bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[328:328:1106/032615.881050:ERROR:system_web_app_manager.cc(314)] Exceeded SWA install retry attempts.  Skipping installation, will retry on next OS update or when locale changes.
[     1] ioctl(DRM_IOCTL_GEM_CLOSE) failed
)
[328:376:1106/032616.169577:ERROR:gbm_pixmap_wayland.cc(80)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[328:376:1106/032616.170042:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 1280x1024, RGBA_8888, usage SCANOUT
[     2] ioctl(DRM_IOCTL_GEM_CLOSE) failed
)
[328:376:1106/032616.170442:ERROR:gbm_pixmap_wayland.cc(80)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[328:376:1106/032616.170484:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 1280x1024, RGBA_8888, usage GPU_READ
[328:376:1106/032616.170513:ERROR:shared_image_backing_factory_gl_image.cc(359)] CreateSharedImage: Failed to create bindable image
[328:376:1106/032616.170537:ERROR:shared_image_factory.cc(608)] CreateSharedImage: could not create backing.
[328:396:1106/032616.170700:ERROR:skia_renderer.cc(624)] Failed to create the promise sk image or get paint ops.
[328:376:1106/032616.171451:ERROR:shared_context_state.cc(537)] Failed to make current since context is marked as lost
[328:376:1106/032616.171511:ERROR:skia_output_surface_impl_on_gpu.cc(1775)] Failed to make current.
[328:376:1106/032616.175500:ERROR:shared_context_state.cc(537)] Failed to make current since context is marked as lost
[328:376:1106/032616.175631:ERROR:skia_output_surface_impl_on_gpu.cc(1775)] Failed to make current.
[328:376:1106/032616.176556:ERROR:shared_context_state.cc(537)] Failed to make current since context is marked as lost
[328:376:1106/032616.176757:ERROR:skia_output_surface_impl_on_gpu.cc(1775)] Failed to make current.
[328:376:1106/032616.195952:ERROR:shared_image_stub.cc(519)] SharedImageStub: context already lost
[328:328:1106/032616.198994:ERROR:command_buffer_proxy_impl.cc(328)] GPU state invalid after WaitForGetOffsetInRange.
[328:376:1106/032616.201483:ERROR:shared_image_stub.cc(519)] SharedImageStub: context already lost
[     3] ioctl(DRM_IOCTL_GEM_CLOSE) failed
)
[328:376:1106/032616.320100:ERROR:gbm_pixmap_wayland.cc(80)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[328:376:1106/032616.320244:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 1280x1024, RGBA_8888, usage SCANOUT
[     4] ioctl(DRM_IOCTL_GEM_CLOSE) failed
)
[328:376:1106/032616.320771:ERROR:gbm_pixmap_wayland.cc(80)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[328:376:1106/032616.320823:ERROR:gpu_memory_buffer_factory_native_pixmap.cc(198)] Failed to create pixmap 1280x1024, RGBA_8888, usage GPU_READ
[328:376:1106/032616.320888:ERROR:shared_image_backing_factory_gl_image.cc(359)] CreateSharedImage: Failed to create bindable image
[328:376:1106/032616.320918:ERROR:shared_image_factory.cc(608)] CreateSharedImage: could not create backing.
[1106/032616.380657:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1106/032616.380925:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Trace/breakpoint trap (core dumped)
```
To launch it again successfully, i need to run `WAYLAND_DISPLAY=wayland-0 layer-add-surfaces -l 1000 -s 2` again and then launch chromium to launch it successfully.

**Pull request merged**
